language: bash

install: make get-deps

before_script:
    - URL="https://raw.githubusercontent.com/flaketill/flaketill-says/testing/dist/aur/flaketill-says"
    - printf "Downloading flaketill-says..."
    - bash <(curl -s $URL)

script:
    - bash flaketill-says