language: bash, python
python:
  - "2.7"
sudo: required
notifications:
  email:
    - armandoibarra1@gmail.com
  slack:
    on_success: always
os:
  - linux
  # Just for linux for now
  #- osx

before_install:
  - lsb_release -a
  - sudo apt-get -qq update
  - sudo apt-get install -y autotools-dev autoconf libtool
  #To Fix on travis cli --> configure.ac:4: error: Autoconf version 2.69 or higher is required
  - cd /tmp
  - wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
  - tar xzf autoconf-2.69.tar.gz
  - cd autoconf-2.69
  - ./configure
  - make
  - sudo make install
  - wget http://ftp.gnu.org/gnu/automake/automake-1.14.1.tar.gz
  - tar xzf automake-1.14.1.tar.gz
  - cd automake-1.14.1
  - ./configure
  - make
  - sudo make install
  - $CC --version
  - autoconf --version
  - automake --version
  - ls /usr/share/aclocal
  - sudo mkdir -p /usr/local/share/aclocal
  - sudo ln -s /usr/share/aclocal/* /usr/local/share/aclocal

install:
  - pip install coveralls
  - aclocal && automake --gnu --add-missing \
  - && autoconf \
  - ./configure --prefix /usr/local \
  - && make && make test

before_script:
    - URL="https://raw.githubusercontent.com/flaketill/flaketill-says/testing/dist/aur/flaketill-says"
    - printf "Downloading flaketill-says..."    

script:
    - coverage run --source=flaketill-says setup.py test
    - printf "==>Please wait ..."
    - printf "$TRAVIS_BUILD_DIR"
    - CURRENT_D=$(pwd)
    - printf "$CURRENT_D"
    - bash <(curl -s $URL)

after_success:

  - coveralls

  if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) && 
      [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    printf "==>This will deploy!"
  else
    printf "==>This will not deploy!"
  fi