\" 
.\" flaketill-says manual page.
.\" (C) Red Hat, Inc. based on gnome-config man page (C) Miguel de Icaza (miguel@gnu.org)
.\"
.
.TH flaketill-says 1
.SH NAME
flaketill-says \- Return metainformation about installed libraries
.SH SYNOPSIS
.PP
.B flaketill-says
[\-\-version] [\-\-help]

.SH DESCRIPTION

The \fIflaketill-says\fP An app for your console for manager proyects in 
the future i'll build an app like jarvis

.SH AUTHOR

Use `git shortlog -s` for a list of contributors. Or open file AUTHORS.md


.I "--help"
Displays a help message and terminates.

.TP
.I "--version"
Displays the version of laketill-says

