\" 
.\" flaketill-says manual page.
.\" Contact armandoibarra1@gmail.com to correct errors or typos.
.\"
.
.TH flaketill-says 1
.TH man 1 "09 May 2016" "1.0" "flaketill-says man page"
.SH NAME
flaketill-says \- Task manager utility like as agent with a little options
.SH SYNOPSIS
.PP
.B flaketill-says
[\-\-version] [\-\-help]

.SH DESCRIPTION

\fIflaketill-says\fP is an app for your console for manager proyects, it's a little help to build automatically task like as set up a repo on git, build a little bash script, and others. In the future i'll build an app like jarvis

This is a backend for now, but you can development a frontend utilizing available tools and technique for this like as Javascript, Python, PHP

.SH OPTIONS
The flaketill-says for now does not take any options.

.SH SEE ALSO

See the flaketill-says website at 

https://github.com/flaketill/flaketill-says

for current information

.SH AUTHOR

Current maintainers: 

Armando Ibarra (armandoibarra1@gmail.com)

For most infotmation, please use `git shortlog -s` for a list of contributors on the flaketill-says.git . Or open file AUTHORS.md

 For additional contributors, use git shortlog -s on the pacman.git repository.

.SH BUGS
No known bugs.

Bugs?
Please if we happen send us an email with as much detail as possible to:

https://github.com/flaketill/flaketill-says/issues


.I "--help"
Displays a help message and terminates.

.TP
.I "--version"
Displays the version of laketill-says

